# Generated by Django 5.2.7 on 2025-11-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
